import { NextResponse } from "next/server";

type RiskLevel = "Low" | "Medium" | "High";

interface LeaderboardRow {
  rank: number;
  name: string;
  /** CSS background string used for the avatar circle. */
  avatar: string;
  verified: boolean;
  strategyType: string;
  sixMonthReturn: string;
  risk: RiskLevel;
  copiers: string;
  minCopy: string;
  winRate: number;
}

/**
 * Mock leaderboard dataset. Seeded with 15 providers per tab so the UI's
 * 5-per-page pagination has three pages to step through. Replace this with a
 * real data source (DB, MT5 mirror, etc.) when the back-end is ready.
 */
const TRENDING: LeaderboardRow[] = [
  {
    rank: 1,
    name: "RTFKT x RIMOWA Meta...",
    avatar: "radial-gradient(circle at 30% 30%, #F472B6 0%, #831843 70%)",
    verified: true,
    strategyType: "Growth",
    sixMonthReturn: "+23.78 %",
    risk: "Medium",
    copiers: "2.3k",
    minCopy: "$250",
    winRate: 81,
  },
  {
    rank: 2,
    name: "EVERYBODYS",
    avatar: "radial-gradient(circle at 40% 30%, #FFFFFF 0%, #67E8F9 80%)",
    verified: true,
    strategyType: "Swing",
    sixMonthReturn: "+67.90 %",
    risk: "Low",
    copiers: "9.1k",
    minCopy: "$150",
    winRate: 75,
  },
  {
    rank: 3,
    name: "DentedFeelsNFT",
    avatar: "radial-gradient(circle at 35% 35%, #93C5FD 0%, #1E3A8A 80%)",
    verified: true,
    strategyType: "Scalping",
    sixMonthReturn: "+32.54 %",
    risk: "Medium",
    copiers: "3.4k",
    minCopy: "$400",
    winRate: 89,
  },
  {
    rank: 4,
    name: "Kitaro World Official",
    avatar: "radial-gradient(circle at 35% 35%, #FCA5A5 0%, #7F1D1D 80%)",
    verified: false,
    strategyType: "Trend",
    sixMonthReturn: "+51.43 %",
    risk: "Medium",
    copiers: "6.7k",
    minCopy: "$300",
    winRate: 90,
  },
  {
    rank: 5,
    name: "Degenheim",
    avatar: "radial-gradient(circle at 35% 35%, #E5E7EB 0%, #4B5563 80%)",
    verified: false,
    strategyType: "Position",
    sixMonthReturn: "+89.21 %",
    risk: "High",
    copiers: "4.2k",
    minCopy: "$200",
    winRate: 61,
  },
  {
    rank: 6,
    name: "NovaQuant",
    avatar: "radial-gradient(circle at 30% 30%, #A7F3D0 0%, #065F46 80%)",
    verified: true,
    strategyType: "Algo",
    sixMonthReturn: "+44.12 %",
    risk: "Medium",
    copiers: "5.1k",
    minCopy: "$350",
    winRate: 83,
  },
  {
    rank: 7,
    name: "VoltCarry",
    avatar: "radial-gradient(circle at 35% 30%, #FDE68A 0%, #B45309 80%)",
    verified: true,
    strategyType: "Carry",
    sixMonthReturn: "+38.65 %",
    risk: "Low",
    copiers: "2.9k",
    minCopy: "$250",
    winRate: 78,
  },
  {
    rank: 8,
    name: "ZephyrPips",
    avatar: "radial-gradient(circle at 40% 35%, #DDD6FE 0%, #4C1D95 80%)",
    verified: false,
    strategyType: "Scalping",
    sixMonthReturn: "+56.07 %",
    risk: "High",
    copiers: "3.8k",
    minCopy: "$500",
    winRate: 64,
  },
  {
    rank: 9,
    name: "OakRidge Macro",
    avatar: "radial-gradient(circle at 30% 30%, #FECACA 0%, #991B1B 80%)",
    verified: true,
    strategyType: "Macro",
    sixMonthReturn: "+29.41 %",
    risk: "Medium",
    copiers: "4.5k",
    minCopy: "$300",
    winRate: 80,
  },
  {
    rank: 10,
    name: "Tidewater Edge",
    avatar: "radial-gradient(circle at 30% 30%, #BAE6FD 0%, #0C4A6E 80%)",
    verified: true,
    strategyType: "Swing",
    sixMonthReturn: "+41.88 %",
    risk: "Low",
    copiers: "6.0k",
    minCopy: "$200",
    winRate: 86,
  },
  {
    rank: 11,
    name: "Ridgeback FX",
    avatar: "radial-gradient(circle at 35% 35%, #FCD34D 0%, #78350F 80%)",
    verified: false,
    strategyType: "Trend",
    sixMonthReturn: "+62.30 %",
    risk: "High",
    copiers: "2.1k",
    minCopy: "$450",
    winRate: 67,
  },
  {
    rank: 12,
    name: "PolarisAlpha",
    avatar: "radial-gradient(circle at 40% 30%, #C7D2FE 0%, #312E81 80%)",
    verified: true,
    strategyType: "Algo",
    sixMonthReturn: "+47.55 %",
    risk: "Medium",
    copiers: "7.4k",
    minCopy: "$300",
    winRate: 84,
  },
  {
    rank: 13,
    name: "Halcyon Trades",
    avatar: "radial-gradient(circle at 30% 30%, #99F6E4 0%, #134E4A 80%)",
    verified: true,
    strategyType: "Growth",
    sixMonthReturn: "+33.92 %",
    risk: "Medium",
    copiers: "3.6k",
    minCopy: "$250",
    winRate: 82,
  },
  {
    rank: 14,
    name: "GoldenHour Cap",
    avatar: "radial-gradient(circle at 35% 30%, #FEF08A 0%, #854D0E 80%)",
    verified: false,
    strategyType: "Position",
    sixMonthReturn: "+19.76 %",
    risk: "Low",
    copiers: "1.8k",
    minCopy: "$150",
    winRate: 73,
  },
  {
    rank: 15,
    name: "EmberLine",
    avatar: "radial-gradient(circle at 30% 30%, #FDBA74 0%, #7C2D12 80%)",
    verified: true,
    strategyType: "Scalping",
    sixMonthReturn: "+71.18 %",
    risk: "High",
    copiers: "5.7k",
    minCopy: "$400",
    winRate: 69,
  },
];

const TOP: LeaderboardRow[] = [
  {
    rank: 1,
    name: "AlphaEdge FX",
    avatar: "radial-gradient(circle at 30% 30%, #FBBF24 0%, #92400E 70%)",
    verified: true,
    strategyType: "Growth",
    sixMonthReturn: "+120.50 %",
    risk: "Medium",
    copiers: "9.4k",
    minCopy: "$300",
    winRate: 92,
  },
  {
    rank: 2,
    name: "ForexMasterPro",
    avatar: "radial-gradient(circle at 30% 30%, #7DD3FC 0%, #075985 70%)",
    verified: true,
    strategyType: "Swing",
    sixMonthReturn: "+95.20 %",
    risk: "Low",
    copiers: "7.8k",
    minCopy: "$250",
    winRate: 88,
  },
  {
    rank: 3,
    name: "StealthTrader",
    avatar: "radial-gradient(circle at 30% 30%, #C4B5FD 0%, #4C1D95 70%)",
    verified: true,
    strategyType: "Scalping",
    sixMonthReturn: "+87.40 %",
    risk: "High",
    copiers: "6.3k",
    minCopy: "$500",
    winRate: 79,
  },
  {
    rank: 4,
    name: "PrimeMarkets EA",
    avatar: "radial-gradient(circle at 30% 30%, #6EE7B7 0%, #064E3B 70%)",
    verified: true,
    strategyType: "Trend",
    sixMonthReturn: "+74.90 %",
    risk: "Medium",
    copiers: "5.5k",
    minCopy: "$400",
    winRate: 84,
  },
  {
    rank: 5,
    name: "EcoTrade Solutions",
    avatar: "radial-gradient(circle at 30% 30%, #FDA4AF 0%, #881337 70%)",
    verified: false,
    strategyType: "Position",
    sixMonthReturn: "+68.10 %",
    risk: "Low",
    copiers: "3.2k",
    minCopy: "$200",
    winRate: 71,
  },
  {
    rank: 6,
    name: "Quanta Sigma",
    avatar: "radial-gradient(circle at 35% 30%, #A5F3FC 0%, #155E75 80%)",
    verified: true,
    strategyType: "Algo",
    sixMonthReturn: "+63.45 %",
    risk: "Medium",
    copiers: "6.8k",
    minCopy: "$350",
    winRate: 86,
  },
  {
    rank: 7,
    name: "NorthStar Trades",
    avatar: "radial-gradient(circle at 30% 35%, #E9D5FF 0%, #6B21A8 80%)",
    verified: true,
    strategyType: "Carry",
    sixMonthReturn: "+59.21 %",
    risk: "Low",
    copiers: "4.7k",
    minCopy: "$250",
    winRate: 90,
  },
  {
    rank: 8,
    name: "Vector Yield",
    avatar: "radial-gradient(circle at 30% 30%, #FDE68A 0%, #92400E 80%)",
    verified: false,
    strategyType: "Macro",
    sixMonthReturn: "+52.66 %",
    risk: "High",
    copiers: "2.6k",
    minCopy: "$500",
    winRate: 65,
  },
  {
    rank: 9,
    name: "Boreal Capital",
    avatar: "radial-gradient(circle at 30% 30%, #BBF7D0 0%, #14532D 80%)",
    verified: true,
    strategyType: "Growth",
    sixMonthReturn: "+48.31 %",
    risk: "Medium",
    copiers: "5.0k",
    minCopy: "$300",
    winRate: 83,
  },
  {
    rank: 10,
    name: "Maven Quant",
    avatar: "radial-gradient(circle at 35% 35%, #F5D0FE 0%, #701A75 80%)",
    verified: true,
    strategyType: "Algo",
    sixMonthReturn: "+45.74 %",
    risk: "Medium",
    copiers: "4.1k",
    minCopy: "$250",
    winRate: 81,
  },
  {
    rank: 11,
    name: "Pinnacle Wave",
    avatar: "radial-gradient(circle at 30% 30%, #FECACA 0%, #7F1D1D 80%)",
    verified: false,
    strategyType: "Swing",
    sixMonthReturn: "+41.09 %",
    risk: "Low",
    copiers: "2.3k",
    minCopy: "$200",
    winRate: 77,
  },
  {
    rank: 12,
    name: "Arcadia Pips",
    avatar: "radial-gradient(circle at 30% 35%, #BFDBFE 0%, #1E3A8A 80%)",
    verified: true,
    strategyType: "Scalping",
    sixMonthReturn: "+37.82 %",
    risk: "High",
    copiers: "3.9k",
    minCopy: "$450",
    winRate: 70,
  },
  {
    rank: 13,
    name: "Cobalt Reserve",
    avatar: "radial-gradient(circle at 30% 30%, #93C5FD 0%, #1E40AF 80%)",
    verified: true,
    strategyType: "Trend",
    sixMonthReturn: "+34.55 %",
    risk: "Medium",
    copiers: "3.5k",
    minCopy: "$300",
    winRate: 82,
  },
  {
    rank: 14,
    name: "AmberPeak FX",
    avatar: "radial-gradient(circle at 35% 30%, #FED7AA 0%, #9A3412 80%)",
    verified: false,
    strategyType: "Position",
    sixMonthReturn: "+28.93 %",
    risk: "Low",
    copiers: "1.9k",
    minCopy: "$150",
    winRate: 74,
  },
  {
    rank: 15,
    name: "Lyric Trading",
    avatar: "radial-gradient(circle at 30% 30%, #DDD6FE 0%, #3730A3 80%)",
    verified: true,
    strategyType: "Macro",
    sixMonthReturn: "+24.40 %",
    risk: "Medium",
    copiers: "2.7k",
    minCopy: "$250",
    winRate: 79,
  },
];

const DATASETS: Record<string, LeaderboardRow[]> = {
  trending: TRENDING,
  top: TOP,
};

export const dynamic = "force-dynamic";

export async function GET(request: Request) {
  const url = new URL(request.url);
  const tab = (url.searchParams.get("tab") || "trending").toLowerCase();
  const page = Math.max(0, parseInt(url.searchParams.get("page") || "0", 10) || 0);
  const limit = Math.max(
    1,
    Math.min(50, parseInt(url.searchParams.get("limit") || "5", 10) || 5),
  );

  const dataset = DATASETS[tab] ?? DATASETS.trending;
  const start = page * limit;
  const rows = dataset.slice(start, start + limit);
  const hasMore = start + limit < dataset.length;

  return NextResponse.json({
    rows,
    hasMore,
    total: dataset.length,
    page,
    limit,
  });
}
